apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ventas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-ventas
  template:
    metadata:
      labels:
        app: backend-ventas
    spec:
      containers:
      - name: backend-ventas
        image: 956050146632.dkr.ecr.us-east-1.amazonaws.com/tienda-ventas:latest
        ports:
        - containerPort: 8082
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"  # Subimos el límite de memoria a 1GB completo para que Java no explote al arrancar
        env:
        - name: DB_ENDPOINT
          value: "mysql-svc"  # Apunta al nombre del Service de arriba
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "tienda_db"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://$(DB_ENDPOINT):$(DB_PORT)/$(DB_NAME)?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true"