# Etapa 1: Construcción con Node
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV VITE_URL_VENTAS=http://a8f4f55528aac49809e673e0d9de7923-928377017.us-east-1.elb.amazonaws.com
ENV VITE_URL_DESPACHOS=http://a81f22891aab04484aa1f3fec124e769-1222862391.us-east-1.elb.amazonaws.com
RUN npm run build

# Etapa 2: Servidor Nginx para exponer la app
FROM nginx:alpine
# Vite por defecto compila en la carpeta 'dist'
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]